---
version: '3.8'
services:
  apache:
    image: kevharv/php-apache-template:latest
    container_name: apache-webserver
    depends_on:
      - mysql
    ports:
      - 80:80
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mysql:
    image: mysql:8.0-debian
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - db.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  db_data: